### ISSUE TITLE
Azure Blob Storageの検証と設置

### ISSUE THREAD

**Issue by nagi-lc3** [hal-tokyo-cello/cello-game#25]
# Blob StorageのCI/CD

- [x] GitHub Workflowコンフィグを設定
- [x] デプロイ確認
- [x] Webpackを取り込む #26 

Blob Storage部分は完成。あとはCDNの完成を待ち、CDNにも自動でデプロイするようにする
CDNのエラーで進みません。

いろいろやってできた！あとは本番環境の作成！

# npmの設定について
```yml:blob_storage.yml
name: blob_storage

# main ブランチに何らかの commit が追加されたら走らせる
on:
  push:
    branches:
      - main

env:
  STORAGE_ACCOUNT_NAME: "infrag01storage01" # ストレージアカウントの名前。書き換えてください
  CDN_PROFILE_NAME: "HAL-TH22-IH4C-IW4C-G01-CDN01" # CDNの名前。書き換えてください
  CDN_ENDPOINT: "cello-infra01" # エンドポイントの名前。書き換えてください
  RESOURCE_GROUP: "HAL-TH22-RG-IH4C-IW4C-G01" # リソースグループを指定
  BLOB_STORAGE_PACKAGE_PATH: "./" # アップロードするディレクトリ。書き換えてください（現在はルートディレクトリすべてをデプロイしている）
  NODE_VERSION: "16.x" # nodeのバージョンを指定。書き換えてください

jobs:
  blob-storage-build-and-deploy:
    name: Blob-storage-build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      ##### webpackの追加設定 #####
      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Resolve Project Dependencies Using Npm
        shell: bash
        run: |
          pushd './${{ env.BLOB_STORAGE_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

      - name: Build App
        run: npx webpack
      ##### webpackの追加設定 ここまで #####

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name ${{ env.STORAGE_ACCOUNT_NAME }} --auth-mode key -d '$web' -s ${{ env.BLOB_STORAGE_PACKAGE_PATH }}

      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths "/*" --profile-name ${{ env.CDN_PROFILE_NAME }} --name ${{ env.CDN_ENDPOINT }} --resource-group ${{ env.RESOURCE_GROUP }}

      - name: Azure logout
        run: |
          az logout
        if: always()

```
ここの
name: Resolve Project Dependencies Using Npm
項目について、フロントがどのように開発しているのか分からないので、何を書けばいいのか分かりません。
フロントに投げていいですか。
また、webpackについても同様です。
